version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5001:5000"
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Super_password"
    ports:
      - "1434:1433"
